module.exports = {
  "be-m1": { "explanation": "To obtain or bring about by discussion.", "explanationIndo": "Memperoleh kesepakatan atau mencapai hasil melalui diskusi (bernegosiasi)." },
  "be-m2": { "explanation": "Income, especially when of a company or organization and of a substantial nature.", "explanationIndo": "Pemasukan atau pendapatan, terutama yang dimiliki oleh sebuah perusahaan dalam jumlah besar." },
  "be-m3": { "explanation": "A person with an interest or concern in something, especially a business.", "explanationIndo": "Seseorang yang memiliki kepentingan atau andil dalam suatu hal, terutama bisnis (pemangku kepentingan)." },
  "be-m4": { "explanation": "A standard or point of reference against which things may be compared or assessed.", "explanationIndo": "Sebuah standar atau titik referensi yang digunakan untuk membandingkan atau menilai (tolok ukur)." },
  "be-m5": { "explanation": "To work jointly on an activity, especially to produce or create something.", "explanationIndo": "Bekerja sama dalam suatu aktivitas untuk memproduksi atau menciptakan sesuatu (berkolaborasi)." },
  "be-m6": { "explanation": "To entrust a task or responsibility to another person, typically one who is less senior than oneself.", "explanationIndo": "Memercayakan tugas atau tanggung jawab kepada orang lain, biasanya bawahan (mendelegasikan)." },
  "be-m7": { "explanation": "To predict or estimate a future event or trend.", "explanationIndo": "Memprediksi atau memperkirakan peristiwa atau tren di masa depan." },
  "be-m8": { "explanation": "To put a decision, plan, agreement into effect.", "explanationIndo": "Menerapkan atau menjalankan sebuah keputusan, rencana, atau kesepakatan." },
  "be-m9": { "explanation": "A thing that motivates or encourages one to do something.", "explanationIndo": "Sesuatu yang memotivasi atau mendorong seseorang untuk melakukan suatu hal (insentif)." },
  "be-m10": { "explanation": "A list of items to be discussed at a formal meeting.", "explanationIndo": "Daftar hal atau rencana yang akan dibahas dalam pertemuan formal (agenda)." },
  "be-h1": { "explanation": "To use something to maximum advantage.", "explanationIndo": "Menggunakan sesuatu untuk keuntungan maksimal (memanfaatkan)." },
  "be-h2": { "explanation": "An asset or object bought or obtained, typically by a library or museum, or a corporate takeover.", "explanationIndo": "Pembelian atau perolehan aset/perusahaan (akuisisi)." },
  "be-h3": { "explanation": "To make or become more diverse or varied.", "explanationIndo": "Membuat atau menjadi lebih beragam/bervariasi (mendiversifikasi)." },
  "be-h4": { "explanation": "To make an organization or system more efficient and effective by employing faster or simpler working methods.", "explanationIndo": "Membuat sistem atau organisasi menjadi lebih efisien dengan metode yang lebih sederhana (menyederhanakan)." },
  "be-h5": { "explanation": "Able to be scaled or climbed; in business, able to grow without being hampered by its structure.", "explanationIndo": "Mampu berkembang dan bertumbuh secara efisien tanpa terhambat struktur aslinya (terukur)." },
  "be-h6": { "explanation": "The state of being responsible for something, especially by law.", "explanationIndo": "Keadaan bertanggung jawab atas sesuatu, terutama secara hukum atau finansial." },
  "be-h7": { "explanation": "The exclusive possession or control of the supply or trade in a commodity or service.", "explanationIndo": "Penguasaan eksklusif atas pasokan atau perdagangan komoditas/layanan (monopoli)." },
  "be-h8": { "explanation": "To wind up the affairs of a company or firm by ascertaining liabilities and apportioning assets.", "explanationIndo": "Mencairkan aset perusahaan atau menyelesaikan utangnya, seringkali untuk menutup bisnis (melikuidasi)." },
  "be-h9": { "explanation": "A company controlled by a holding company.", "explanationIndo": "Perusahaan yang dikendalikan oleh perusahaan induk (anak perusahaan)." },
  "be-h10": { "explanation": "The interaction or cooperation of two or more organizations, substances, or other agents to produce a combined effect greater than the sum of their separate effects.", "explanationIndo": "Kerja sama dua organisasi atau lebih yang menghasilkan efek gabungan yang lebih besar daripada efek terpisahnya (sinergi)." },
  "be-x1": { "explanation": "The action or process of gradually writing off the initial cost of an asset or paying off a debt.", "explanationIndo": "Proses secara bertahap menghapus biaya awal aset atau melunasi utang (amortisasi)." },
  "be-x2": { "explanation": "Involving trust, especially with regard to the relationship between a trustee and a beneficiary.", "explanationIndo": "Melibatkan kepercayaan hukum, khususnya terkait tanggung jawab mengelola aset pihak lain (fidusia)." },
  "be-x3": { "explanation": "Money paid for work or a service.", "explanationIndo": "Uang atau imbalan yang dibayarkan untuk pekerjaan atau layanan (remunerasi)." },
  "be-x4": { "explanation": "A number of different things or parts that are put or grouped together to form a whole but remain distinct entities.", "explanationIndo": "Sejumlah hal berbeda yang disatukan untuk membentuk suatu kesatuan bisnis besar (konglomerat)." },
  "aw-m1": { "explanation": "To examine methodically and in detail the constitution or structure of something.", "explanationIndo": "Memeriksa secara metodis dan terperinci terhadap struktur atau susunan sesuatu (menganalisis)." },
  "aw-m2": { "explanation": "To obtain something from a specified source.", "explanationIndo": "Memperoleh sesuatu dari sumber yang ditentukan." },
  "aw-m3": { "explanation": "To make an action or process easy or easier.", "explanationIndo": "Membuat suatu tindakan atau proses menjadi lebih mudah (memfasilitasi)." },
  "aw-m4": { "explanation": "To evaluate or estimate the nature, ability, or quality of.", "explanationIndo": "Mengevaluasi atau memperkirakan sifat, kemampuan, atau kualitas sesuatu (menilai)." },
  "aw-m5": { "explanation": "An abstract idea; a general notion.", "explanationIndo": "Ide abstrak atau gagasan umum." },
  "aw-m6": { "explanation": "The circumstances that form the setting for an event, statement, or idea.", "explanationIndo": "Keadaan yang membentuk latar belakang suatu peristiwa, pernyataan, atau ide (konteks)." },
  "aw-m7": { "explanation": "To state or describe exactly the nature, scope, or meaning of something.", "explanationIndo": "Menyatakan atau menggambarkan secara pasti makna dari sesuatu (mendefinisikan)." },
  "aw-m8": { "explanation": "To set up on a firm or permanent basis.", "explanationIndo": "Mendirikan atau menetapkan dengan dasar yang kuat atau permanen." },
  "aw-m9": { "explanation": "A circumstance, fact, or influence that contributes to a result or outcome.", "explanationIndo": "Kondisi, fakta, atau pengaruh yang berkontribusi terhadap suatu hasil (faktor)." },
  "aw-m10": { "explanation": "To point out; show.", "explanationIndo": "Menunjukkan; mengindikasikan." },
  "aw-h1": { "explanation": "A supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation.", "explanationIndo": "Penjelasan sementara berdasarkan bukti terbatas yang digunakan sebagai titik awal penyelidikan (hipotesis)." },
  "aw-h2": { "explanation": "A fact or situation that is observed to exist or happen, especially one whose cause or explanation is in question.", "explanationIndo": "Fakta atau situasi luar biasa yang teramati terjadi di alam atau masyarakat (fenomena)." },
  "aw-h3": { "explanation": "To make something by combining different things.", "explanationIndo": "Membuat atau membentuk sesuatu dengan menggabungkan hal-hal yang berbeda (menyintesis)." },
  "aw-h4": { "explanation": "A system of methods used in a particular area of study or activity.", "explanationIndo": "Sistem metode yang digunakan dalam bidang studi atau aktivitas tertentu (metodologi)." },
  "aw-h5": { "explanation": "To have a mutual relationship or connection, in which one thing affects or depends on another.", "explanationIndo": "Memiliki hubungan sebab-akibat timbal balik (berkorelasi)." },
  "aw-h6": { "explanation": "The conclusion that can be drawn from something, although it is not explicitly stated.", "explanationIndo": "Kesimpulan atau efek jangka panjang yang dapat ditarik, meskipun tidak dinyatakan secara eksplisit (implikasi)." },
  "aw-h7": { "explanation": "Existing in something as a permanent, essential, or characteristic attribute.", "explanationIndo": "Ada dalam sesuatu sebagai atribut yang permanen dan esensial (melekat)." },
  "aw-h8": { "explanation": "To be a part of a whole.", "explanationIndo": "Menjadi bagian dari keseluruhan atau membentuk suatu entitas." },
  "aw-h9": { "explanation": "Coming after something in time; following.", "explanationIndo": "Datang setelah sesuatu seiring waktu; mengikuti setelahnya (selanjutnya)." },
  "aw-h10": { "explanation": "Based on, concerned with, or verifiable by observation or experience rather than theory or pure logic.", "explanationIndo": "Berdasarkan pengamatan atau pengalaman langsung di lapangan (empiris)." },
  "aw-x1": { "explanation": "A typical example or pattern of something; a model.", "explanationIndo": "Contoh atau pola yang menjadi model acuan dalam suatu bidang (paradigma)." },
  "aw-x2": { "explanation": "The theory of knowledge, especially with regard to its methods, validity, and scope.", "explanationIndo": "Cabang filsafat yang mempelajari sumber, metode, dan batas pengetahuan manusia (epistemologi)." },
  "aw-x3": { "explanation": "The branch of metaphysics dealing with the nature of being.", "explanationIndo": "Cabang filsafat yang mempelajari hakikat keberadaan dan realitas (ontologi)." },
  "aw-x4": { "explanation": "Enabling a person to discover or learn something for themselves.", "explanationIndo": "Pendekatan pemecahan masalah dengan metode praktis yang memungkinkan pembelajaran mandiri (heuristik)." },
  "pv-e1": { "explanation": "To understand or solve something.", "explanationIndo": "Mencari tahu, memahami, atau memecahkan suatu masalah." },
  "pv-e2": { "explanation": "To cease making an effort; resign oneself to failure.", "explanationIndo": "Berhenti berusaha; menyerah atau pasrah pada kegagalan." },
  "pv-e3": { "explanation": "To prepare or arrange something for use.", "explanationIndo": "Mempersiapkan, mendirikan, atau mengatur sesuatu agar siap digunakan." },
  "pv-e4": { "explanation": "To engage in physical exercise, or to solve a problem.", "explanationIndo": "Berolahraga atau mencari solusi untuk menyelesaikan masalah." },
  "pv-e5": { "explanation": "To stop sleeping.", "explanationIndo": "Berhenti tidur dan membuka mata; bangun." },
  "pv-e6": { "explanation": "To move from a standing position to a sitting one.", "explanationIndo": "Berpindah dari posisi berdiri ke posisi duduk." },
  "pv-e7": { "explanation": "To rise to one's feet.", "explanationIndo": "Bangkit dari duduk dan berdiri di atas kaki." },
  "pv-e8": { "explanation": "To start the operation of a machine or device.", "explanationIndo": "Memulai pengoperasian mesin atau perangkat elektronik (menyalakan)." },
  "pv-e9": { "explanation": "To stop the operation of a machine or device.", "explanationIndo": "Menghentikan pengoperasian mesin atau perangkat (mematikan)." },
  "pv-e10": { "explanation": "To attempt to find someone or something.", "explanationIndo": "Berusaha menemukan seseorang atau sesuatu (mencari)." },
  "pv-m1": { "explanation": "To stop functioning (for machines); to lose control of one's emotions.", "explanationIndo": "Berhenti berfungsi (rusak/mogok) atau kehilangan kendali emosi." },
  "pv-m2": { "explanation": "To introduce a topic into a conversation; to raise a child.", "explanationIndo": "Mengangkat topik pembicaraan atau membesarkan anak." },
  "pv-m3": { "explanation": "To cancel an event or agreement.", "explanationIndo": "Membatalkan suatu acara atau kesepakatan secara resmi." },
  "pv-m4": { "explanation": "To meet or find someone or something by chance.", "explanationIndo": "Menemukan atau bertemu dengan seseorang secara kebetulan." },
  "pv-m5": { "explanation": "To feel pleased and excited about something that is going to happen.", "explanationIndo": "Merasa senang dan sangat menantikan sesuatu yang akan terjadi." },
  "pv-m6": { "explanation": "To invent a story or lie; to forgive someone after an argument.", "explanationIndo": "Mengarang cerita/kebohongan; berdamai setelah bertengkar." },
  "pv-m7": { "explanation": "To delay or postpone something.", "explanationIndo": "Menunda sesuatu ke waktu yang lebih lambat." },
  "pv-m8": { "explanation": "To have none left; to exhaust a supply.", "explanationIndo": "Tidak memiliki sisa sama sekali (kehabisan persediaan)." },
  "pv-m9": { "explanation": "To assume control of something.", "explanationIndo": "Mengambil alih kendali atau kepemimpinan atas sesuatu." },
  "pv-m10": { "explanation": "To refuse a request or offer.", "explanationIndo": "Menolak sebuah permintaan, lamaran, atau tawaran." },
  "pv-h1": { "explanation": "To escape blame or punishment for a wrong action.", "explanationIndo": "Lolos dari hukuman atau konsekuensi setelah berbuat salah." },
  "pv-h2": { "explanation": "To tolerate or endure something annoying or unpleasant.", "explanationIndo": "Menoleransi atau menanggung hal yang mengganggu atau tidak menyenangkan." },
  "pv-h3": { "explanation": "To think that you are better than someone else.", "explanationIndo": "Memandang rendah atau meremehkan orang lain." },
  "pv-h4": { "explanation": "To do something you have not been able to do recently.", "explanationIndo": "Mengerjakan sesuatu untuk menyusul ketertinggalan." },
  "pv-h5": { "explanation": "To have an argument and stop being friends.", "explanationIndo": "Bertengkar dengan seseorang dan berhenti berteman." },
  "pv-h6": { "explanation": "To withdraw a claim or assertion in the face of opposition.", "explanationIndo": "Mengalah atau menarik kembali pernyataan karena tekanan oposisi." },
  "pv-h7": { "explanation": "To be reduced to its most essential part.", "explanationIndo": "Meringkas hingga ke inti atau bagian terpentingnya (pada intinya)." },
  "pv-h8": { "explanation": "To improve or refresh one's knowledge of something.", "explanationIndo": "Menyegarkan kembali ingatan atau mengasah keahlian lama." },
  "pv-h9": { "explanation": "To attribute something to a particular cause.", "explanationIndo": "Menganggap sesuatu sebagai akibat atau hasil dari hal tertentu." },
  "pv-h10": { "explanation": "To resolve or clear up difficulties or problems.", "explanationIndo": "Menyelesaikan masalah kecil atau membereskan perbedaan." },
  "id-m1": { "explanation": "Something that is very easy to do.", "explanationIndo": "Sesuatu tugas yang sangat mudah untuk dilakukan." },
  "id-m2": { "explanation": "To initiate conversation and relieve tension in a social setting.", "explanationIndo": "Memulai percakapan untuk mengurangi ketegangan dan mencairkan suasana." },
  "id-m3": { "explanation": "Feeling slightly ill or sick.", "explanationIndo": "Merasa sedikit sakit atau kurang sehat." },
  "id-m4": { "explanation": "Happening very rarely.", "explanationIndo": "Terjadi sangat jarang." },
  "id-m5": { "explanation": "To reveal secret information unintentionally or indiscreetly.", "explanationIndo": "Membocorkan rahasia atau informasi yang seharusnya disembunyikan." },
  "id-m6": { "explanation": "To avoid talking about what is important.", "explanationIndo": "Berbicara berbelit-belit dan menghindari inti pembicaraan." },
  "id-m7": { "explanation": "To stop working on something for the rest of the day.", "explanationIndo": "Memutuskan untuk berhenti bekerja pada sesuatu untuk hari itu." },
  "id-m8": { "explanation": "To remain persistent and not give up in a difficult situation.", "explanationIndo": "Tetap bertahan dan tidak menyerah dalam situasi sulit." },
  "id-m9": { "explanation": "To go to bed in order to sleep.", "explanationIndo": "Pergi ke tempat tidur untuk tidur." },
  "id-m10": { "explanation": "To be alert, focused, and quick to react.", "explanationIndo": "Sangat tanggap, waspada, dan fokus pada apa yang sedang terjadi." },
  "id-h1": { "explanation": "To describe exactly what is causing a situation or problem.", "explanationIndo": "Mendeskripsikan dengan sangat akurat atau bertindak tepat sasaran." },
  "id-h2": { "explanation": "To be extremely expensive.", "explanationIndo": "Menelan biaya yang sangat mahal." },
  "id-h3": { "explanation": "To decide to do something difficult or unpleasant that one has been putting off.", "explanationIndo": "Memaksa diri menerima situasi sulit yang sudah tidak bisa dihindari lagi." },
  "id-h4": { "explanation": "To work late into the night.", "explanationIndo": "Bekerja atau belajar hingga larut malam (begadang)." },
  "id-h5": { "explanation": "To reveal a secret carelessly or by mistake.", "explanationIndo": "Membocorkan rahasia tanpa sengaja atau karena kecerobohan." },
  "id-h6": { "explanation": "It is up to you to take the next step or make the next decision.", "explanationIndo": "Kini giliranmu untuk bertindak atau membuat keputusan." },
  "id-h7": { "explanation": "To just barely succeed in doing something.", "explanationIndo": "Nyaris atau hampir saja gagal dalam melakukan sesuatu." },
  "id-h8": { "explanation": "To do something poorly or cheaply in order to save time or money.", "explanationIndo": "Mengambil jalan pintas dengan mengorbankan kualitas demi menghemat waktu atau uang." },
  "id-h9": { "explanation": "An obvious problem or issue that people avoid discussing.", "explanationIndo": "Masalah besar yang sangat jelas tetapi dihindari untuk dibahas." },
  "id-h10": { "explanation": "To join a popular trend or activity just because others are doing it.", "explanationIndo": "Ikut-ikutan tren atau aktivitas hanya karena sedang populer." },
  "usr-1": { "explanation": "To suffer from a continuous, dull pain or intense emotional sorrow.", "explanationIndo": "Menderita rasa sakit yang terus-menerus, atau kesedihan yang mendalam (ngilu/sakit)." },
  "usr-2": { "explanation": "A phrase indicating that a particular action is one's personal habit or tradition.", "explanationIndo": "Sebuah frasa yang menunjukkan bahwa suatu tindakan merupakan kebiasaan atau tradisi pribadi seseorang." },
  "usr-3": { "explanation": "To eat food very quickly and greedily.", "explanationIndo": "Makan makanan dengan sangat cepat dan rakus (melahap)." },
  "usr-4": { "explanation": "Past tense of eating greedily; or the sound made by a turkey.", "explanationIndo": "Bentuk lampau dari makan dengan rakus; atau suara yang dihasilkan kalkun." },
  "usr-5": { "explanation": "Quick and light in movement or action; agile.", "explanationIndo": "Bergerak dengan cepat dan ringan; gesit atau lincah." },
  "usr-6": { "explanation": "Plural of thief; people who steal another person's property secretly.", "explanationIndo": "Bentuk jamak dari pencuri; orang-orang yang mencuri harta benda orang lain secara diam-diam." },
  "usr-7": { "explanation": "The land at either edge of a river.", "explanationIndo": "Daratan yang berada di tepi sebuah sungai." },
  "usr-8": { "explanation": "A strong and rapid flow of water in a river or ocean.", "explanationIndo": "Aliran air yang kuat dan bergerak cepat di sungai atau laut (arus deras)." },
  "usr-9": { "explanation": "Extending or directly underneath something; below.", "explanationIndo": "Membentang atau tepat berada di bawah sesuatu." },
  "usr-10": { "explanation": "To find oneself underneath something yet again.", "explanationIndo": "Menemukan diri sendiri di bawah sesuatu untuk kesekian kalinya." },
  "usr-11": { "explanation": "Animal hair that is soaked with water.", "explanationIndo": "Rambut hewan (bulu) yang basah kuyup karena air." },
  "usr-12": { "explanation": "To continue to function well or exist over a period of time.", "explanationIndo": "Terus berfungsi atau bertahan dalam jangka waktu yang lama (awet)." },
  "usr-13": { "explanation": "A dessert or sweet sauce made with milk and eggs, or cooked with flour.", "explanationIndo": "Hidangan penutup atau saus manis yang terbuat dari susu dan telur (vla)." },
  "usr-14": { "explanation": "Past tense of shake; to move irregularly, or to be deeply shocked or surprised.", "explanationIndo": "Bentuk lampau dari mengguncang; atau sangat terkejut dan terguncang." },
  "usr-15": { "explanation": "Said or shouted repeatedly in a singsong tone.", "explanationIndo": "Dikatakan atau diteriakkan secara berulang-ulang dengan nada seperti nyanyian (melantunkan)." },
  "usr-16": { "explanation": "To raise one's sweater or pullover clothing.", "explanationIndo": "Mengangkat pakaian hangat (sweter) milik seseorang." },
  "usr-17": { "explanation": "In a way that shows great happiness or joy at a victory or achievement.", "explanationIndo": "Dengan cara yang menunjukkan kebahagiaan besar atas kemenangan atau pencapaian." },
  "usr-18": { "explanation": "Adult people, especially as seen from a child's perspective.", "explanationIndo": "Orang dewasa, terutama dari sudut pandang anak-anak." },
  "usr-19": { "explanation": "A merry-go-round, or a conveying system for luggage at an airport.", "explanationIndo": "Komidi putar, atau ban berjalan otomatis pengambil koper di bandara." },
  "usr-20": { "explanation": "Sitting down on a seat next to the airport luggage conveyor belt.", "explanationIndo": "Duduk di kursi yang berada tepat di sebelah ban berjalan koper di bandara." },
  "usr-21": { "explanation": "Suitcases or other bags in which to pack personal belongings for traveling.", "explanationIndo": "Koper atau tas lain untuk mengemas barang-barang pribadi untuk bepergian (barang bawaan)." },
  "usr-22": { "explanation": "A man's headdress, consisting of a long length of cotton or silk wound around a cap.", "explanationIndo": "Penutup kepala pria, biasanya terdiri dari kain katun atau sutra panjang yang dililitkan." },
  "usr-23": { "explanation": "Curious or inquiring; given to asking questions.", "explanationIndo": "Sangat penasaran; banyak bertanya dan ingin tahu segalanya (kepo)." },
  "usr-24": { "explanation": "Proceeding forward in orderly and highly organized rows.", "explanationIndo": "Maju ke depan dalam barisan yang sangat teratur dan rapi." },
  "usr-25": { "explanation": "To be silent, morose, and bad-tempered out of annoyance or disappointment.", "explanationIndo": "Menjadi pendiam, cemberut, dan marah karena kesal atau kecewa (merajuk)." },
  "usr-26": { "explanation": "To leave a place while visibly angry, pouting, or throwing a silent tantrum.", "explanationIndo": "Pergi dari suatu tempat dengan raut wajah marah atau merajuk." },
  "usr-27": { "explanation": "To stack one item on top of another.", "explanationIndo": "Menumpuk satu barang di atas barang lainnya." },
  "usr-28": { "explanation": "To be made to feel sorrowful or unhappy.", "explanationIndo": "Dibuat merasa sangat berduka, kecewa, atau sedih." },
  "usr-29": { "explanation": "During the time that, or at the same time as; although.", "explanationIndo": "Pada saat yang sama dengan; atau bisa juga berarti 'padahal/sementara itu'." }
};
