module.exports = {
  "ie-m1": { "explanation": "To distribute resources or duties for a particular purpose.", "explanationIndo": "Mendistribusikan sumber daya atau tugas untuk tujuan tertentu (mengalokasikan)." },
  "ie-m2": { "explanation": "Favorable or advantageous; resulting in good.", "explanationIndo": "Menguntungkan; menghasilkan sesuatu yang baik (bermanfaat)." },
  "ie-m3": { "explanation": "To begin or start something.", "explanationIndo": "Memulai sesuatu, seperti proyek atau acara." },
  "ie-m4": { "explanation": "Able to exist or occur together without conflict.", "explanationIndo": "Mampu ada atau terjadi bersama tanpa konflik (kompatibel)." },
  "ie-m5": { "explanation": "To give someone something, typically money, in recognition of loss, suffering, or injury.", "explanationIndo": "Memberikan sesuatu (biasanya uang) sebagai pengakuan atas kerugian atau penderitaan (mengkompensasi)." },
  "ie-m6": { "explanation": "To clearly show the existence or truth of something by giving proof or evidence.", "explanationIndo": "Menunjukkan dengan jelas kebenaran sesuatu dengan memberikan bukti (mendemonstrasikan)." },
  "ie-m7": { "explanation": "To represent something as being larger, greater, better, or worse than it really is.", "explanationIndo": "Mewakili sesuatu sebagai lebih besar atau lebih buruk dari kenyataannya (membesar-besarkan)." },
  "ie-m8": { "explanation": "To put a decision, plan, agreement into effect.", "explanationIndo": "Mewujudkan atau menjalankan suatu keputusan, rencana, atau kesepakatan (menerapkan)." },
  "ie-m9": { "explanation": "To show or prove to be right or reasonable.", "explanationIndo": "Menunjukkan atau membuktikan bahwa sesuatu itu benar atau masuk akal (membenarkan)." },
  "ie-m10": { "explanation": "To make partial or minor changes to something, typically so as to improve it.", "explanationIndo": "Melakukan perubahan sebagian atau kecil pada sesuatu untuk memperbaikinya (memodifikasi)." },
  "ie-h1": { "explanation": "Open to more than one interpretation; having a double meaning.", "explanationIndo": "Terbuka untuk lebih dari satu interpretasi; memiliki makna ganda atau tidak jelas (ambigu)." },
  "ie-h2": { "explanation": "Logical and consistent; united as or forming a whole.", "explanationIndo": "Logis dan konsisten; bersatu membentuk suatu kesatuan (koheren)." },
  "ie-h3": { "explanation": "Complete; including all or nearly all elements or aspects of something.", "explanationIndo": "Lengkap; mencakup semua atau hampir semua elemen atau aspek dari sesuatu (komprehensif)." },
  "ie-h4": { "explanation": "A general agreement among a group of people.", "explanationIndo": "Kesepakatan umum di antara sekelompok orang (konsensus)." },
  "ie-h5": { "explanation": "A limitation or restriction.", "explanationIndo": "Sebuah batasan atau hambatan (kendala)." },
  "ie-h6": { "explanation": "To take over the place, position, or role of someone or something.", "explanationIndo": "Mengambil alih tempat, posisi, atau peran seseorang atau sesuatu (menggantikan)." },
  "ie-h7": { "explanation": "Planned for or about to happen in the near future.", "explanationIndo": "Direncanakan atau akan segera terjadi dalam waktu dekat (yang akan datang)." },
  "ie-h8": { "explanation": "Mainly; for the most part.", "explanationIndo": "Terutama; untuk sebagian besar." },
  "ie-h9": { "explanation": "The quality or state of being exposed to the possibility of being attacked or harmed.", "explanationIndo": "Kualitas atau keadaan di mana seseorang/sesuatu terbuka terhadap kemungkinan diserang atau disakiti (kerentanan)." },
  "ie-h10": { "explanation": "Able to be maintained at a certain rate or level; conserving an ecological balance.", "explanationIndo": "Dapat dipertahankan pada tingkat tertentu tanpa merusak keseimbangan lingkungan (berkelanjutan)." },
  "ie-x1": { "explanation": "To examine or inspect closely and thoroughly.", "explanationIndo": "Memeriksa atau meneliti dengan sangat saksama dan menyeluruh." },
  "ie-x2": { "explanation": "To provide evidence to support or prove the truth of something.", "explanationIndo": "Memberikan bukti untuk mendukung atau membuktikan kebenaran sesuatu (membuktikan)." },
  "ie-x3": { "explanation": "Never done or known before.", "explanationIndo": "Belum pernah dilakukan atau diketahui sebelumnya." },
  "ie-x4": { "explanation": "Present, appearing, or found everywhere.", "explanationIndo": "Hadir, muncul, atau dapat ditemukan di mana-mana." },
  "ie-x5": { "explanation": "Seemingly absurd or self-contradictory.", "explanationIndo": "Tampaknya konyol atau bertentangan dengan dirinya sendiri (paradoks)." },
  "sat-m1": { "explanation": "Truthful and straightforward; frank.", "explanationIndo": "Jujur dan berterus terang; blak-blakan." },
  "sat-m2": { "explanation": "Having or showing care and conscientiousness in one's work or duties.", "explanationIndo": "Memiliki atau menunjukkan kepedulian dan kehati-hatian dalam pekerjaan (rajin)." },
  "sat-m3": { "explanation": "A sentimental longing or wistful affection for the past.", "explanationIndo": "Kerinduan sentimental atau kasih sayang yang mendalam terhadap masa lalu." },
  "sat-m4": { "explanation": "Existing or occurring at or on the surface; not thorough, deep, or complete.", "explanationIndo": "Hanya ada di permukaan; tidak menyeluruh atau mendalam (dangkal)." },
  "sat-m5": { "explanation": "Very skilled or proficient at something.", "explanationIndo": "Sangat terampil atau mahir dalam suatu hal." },
  "sat-m6": { "explanation": "To make a statement or situation less confused and more comprehensible.", "explanationIndo": "Membuat suatu pernyataan atau situasi menjadi lebih jelas dan mudah dipahami." },
  "sat-m7": { "explanation": "Featuring new methods; advanced and original.", "explanationIndo": "Menampilkan metode baru; canggih dan orisinal (inovatif)." },
  "sat-m8": { "explanation": "Expressed clearly; easy to understand.", "explanationIndo": "Diungkapkan dengan jelas; sangat mudah dipahami (jernih)." },
  "sat-m9": { "explanation": "Unassuming or moderate in the estimation of one's abilities or achievements.", "explanationIndo": "Rendah hati; tidak melebih-lebihkan kemampuan atau pencapaian sendiri." },
  "sat-m10": { "explanation": "Producing many works, results, or offspring.", "explanationIndo": "Menghasilkan banyak karya, hasil, atau keturunan (sangat produktif)." },
  "sat-h1": { "explanation": "To shorten a book, movie, speech, or other text without losing the sense.", "explanationIndo": "Mempersingkat buku, film, pidato, atau teks tanpa kehilangan makna aslinya (meringkas)." },
  "sat-h2": { "explanation": "Well meaning and kindly.", "explanationIndo": "Penuh niat baik dan sangat ramah/baik hati." },
  "sat-h3": { "explanation": "Fluent or persuasive in speaking or writing.", "explanationIndo": "Fasih atau persuasif dalam berbicara atau menulis." },
  "sat-h4": { "explanation": "Having or displaying a passionate intensity.", "explanationIndo": "Memiliki atau menampilkan intensitas yang penuh gairah (bersemangat)." },
  "sat-h5": { "explanation": "Treating all rivals or disputants equally; fair and just.", "explanationIndo": "Memperlakukan semua pihak secara setara; adil dan tidak memihak." },
  "sat-h6": { "explanation": "Affected by lethargy; sluggish and apathetic.", "explanationIndo": "Terdampak rasa lesu; lamban dan apatis/kurang bersemangat." },
  "sat-h7": { "explanation": "Showing great attention to detail; very careful and precise.", "explanationIndo": "Menunjukkan perhatian besar pada detail; sangat hati-hati dan teliti." },
  "sat-h8": { "explanation": "Not discovered or known about; uncertain.", "explanationIndo": "Belum ditemukan atau diketahui; tidak jelas atau samar." },
  "sat-h9": { "explanation": "Able to withstand or recover quickly from difficult conditions.", "explanationIndo": "Mampu bertahan atau pulih dengan cepat dari kondisi yang sulit (tangguh)." },
  "sat-h10": { "explanation": "To regard with great respect; revere.", "explanationIndo": "Memandang atau memperlakukan dengan rasa hormat yang sangat besar." },
  "sat-x1": { "explanation": "Fond of company; sociable.", "explanationIndo": "Suka ditemani; sangat suka bergaul dan bersosialisasi." },
  "sat-x2": { "explanation": "Lacking significance through having been overused; unoriginal and trite.", "explanationIndo": "Kehilangan makna karena terlalu sering digunakan; tidak orisinal (klise)." },
  "sat-x3": { "explanation": "To place or deal with close together for contrasting effect.", "explanationIndo": "Menempatkan atau menyatukan sesuatu secara berdekatan untuk memberikan efek kontras (menyandingkan)." },
  "sat-x4": { "explanation": "Tending to keep a firm hold of something; clinging or adhering closely.", "explanationIndo": "Cenderung memegang teguh sesuatu; gigih atau tangguh." },
  "sat-x5": { "explanation": "Lasting for a very short time.", "explanationIndo": "Berlangsung untuk waktu yang sangat singkat (sementara/fana)." },
  "be-e1": { "explanation": "An assembly of people, especially the members of a society or committee, for discussion.", "explanationIndo": "Kumpulan orang yang bertemu untuk melakukan diskusi profesional (rapat)." },
  "be-e2": { "explanation": "A person or organization using the services of a lawyer or other professional person or company.", "explanationIndo": "Seseorang atau organisasi yang menggunakan layanan seorang profesional (klien)." },
  "be-e3": { "explanation": "A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work.", "explanationIndo": "Ruangan atau bangunan yang digunakan sebagai tempat kerja profesional atau komersial." },
  "be-e4": { "explanation": "A person in charge of a worker or organization.", "explanationIndo": "Orang yang bertanggung jawab atas pekerja atau organisasi (atasan)." },
  "be-e5": { "explanation": "A fixed regular payment, typically paid on a monthly or biweekly basis.", "explanationIndo": "Pembayaran tetap secara teratur, biasanya dibayarkan setiap bulan (gaji)." },
  "be-e6": { "explanation": "A paid position of regular employment.", "explanationIndo": "Posisi berbayar dari pekerjaan rutin." },
  "be-e7": { "explanation": "A commercial business.", "explanationIndo": "Sebuah entitas bisnis komersial (perusahaan)." },
  "be-e8": { "explanation": "To give or hand over something in exchange for money.", "explanationIndo": "Menyerahkan sesuatu sebagai ganti dari uang (menjual)." },
  "be-e9": { "explanation": "To obtain in exchange for payment.", "explanationIndo": "Mendapatkan sesuatu dengan cara memberikan pembayaran uang (membeli)." },
  "be-e10": { "explanation": "A group of individuals working together to achieve their goal.", "explanationIndo": "Sekelompok individu yang bekerja sama untuk mencapai tujuan mereka." }
};
