module.exports = {
  "dc-e1": { "explanation": "To go somewhere with someone as a companion or escort.", "explanationIndo": "Pergi ke suatu tempat bersama seseorang sebagai teman atau pendamping." },
  "dc-e2": { "explanation": "Pleasing the senses or mind aesthetically; possessing beauty.", "explanationIndo": "Menyenangkan indra atau pikiran secara estetika; memiliki keindahan." },
  "dc-e3": { "explanation": "Highly pleasant to the taste or smell; very tasty.", "explanationIndo": "Sangat menyenangkan untuk dicicipi atau dicium; sangat enak." },
  "dc-e4": { "explanation": "Kind, pleasant, and approachable towards others.", "explanationIndo": "Baik hati, menyenangkan, dan mudah didekati oleh orang lain." },
  "dc-e5": { "explanation": "An action or judgment that is misguided or wrong.", "explanationIndo": "Sebuah tindakan atau penilaian yang keliru atau salah." },
  "dc-e6": { "explanation": "Making little or no noise; silent or peaceful.", "explanationIndo": "Sedikit atau tidak mengeluarkan suara; sunyi atau damai." },
  "dc-e7": { "explanation": "To perceive the intended meaning of words, a language, or a person.", "explanationIndo": "Memahami makna yang dimaksudkan dari kata-kata, bahasa, atau seseorang." },
  "dc-e8": { "explanation": "The state of the atmosphere at a place and time regarding heat, dryness, sunshine, wind, rain, etc.", "explanationIndo": "Keadaan atmosfer di suatu tempat dan waktu terkait cuaca panas, kering, sinar matahari, angin, hujan, dll." },
  "dc-e9": { "explanation": "The period of time between midnight and noon, especially from sunrise to noon.", "explanationIndo": "Periode waktu antara tengah malam dan siang, terutama dari matahari terbit hingga tengah hari." },
  "dc-e10": { "explanation": "A condition of body and mind which typically recurs for several hours every night, in which the nervous system is inactive.", "explanationIndo": "Kondisi tubuh dan pikiran yang biasanya berulang selama beberapa jam setiap malam, di mana sistem saraf sedang tidak aktif." },
  "dc-e11": { "explanation": "Feeling or showing pleasure or contentment.", "explanationIndo": "Merasakan atau menunjukkan kesenangan atau kepuasan." },
  "dc-e12": { "explanation": "Feeling or showing sorrow; unhappy.", "explanationIndo": "Merasakan atau menunjukkan kesedihan; tidak bahagia." },
  "dc-e13": { "explanation": "In need of sleep or rest; weary.", "explanationIndo": "Membutuhkan tidur atau istirahat; lelah." },
  "dc-m1": { "explanation": "To give reasons or cite evidence in support of an idea, action, or theory, typically with the aim of persuading others.", "explanationIndo": "Memberikan alasan atau bukti untuk mendukung suatu ide, tindakan, atau teori, biasanya dengan tujuan membujuk orang lain." },
  "dc-m2": { "explanation": "To express dissatisfaction or annoyance about something.", "explanationIndo": "Menyatakan ketidakpuasan atau kejengkelan tentang sesuatu." },
  "dc-m3": { "explanation": "To express regret for something that one has done wrong.", "explanationIndo": "Menyatakan penyesalan atas sesuatu yang telah dilakukan dengan salah." },
  "dc-m4": { "explanation": "To convince someone to do or believe something through reasoning or argument.", "explanationIndo": "Meyakinkan seseorang untuk melakukan atau mempercayai sesuatu melalui alasan atau argumen." },
  "dc-m5": { "explanation": "Fitting in well with a person's needs, activities, and plans; causing little trouble or effort.", "explanationIndo": "Sesuai dengan kebutuhan, aktivitas, dan rencana seseorang; tidak merepotkan atau praktis." },
  "dc-m6": { "explanation": "To recognize the full worth of something; to be grateful for.", "explanationIndo": "Menyadari nilai penuh dari sesuatu; bersyukur atas sesuatu." },
  "dc-m7": { "explanation": "Having or showing dogged determination not to change one's attitude or position on something.", "explanationIndo": "Memiliki atau menunjukkan tekad kuat untuk tidak mengubah sikap atau pendirian mengenai sesuatu." },
  "dc-m8": { "explanation": "Casual conversations or reports about other people, typically involving details that are not confirmed as being true.", "explanationIndo": "Percakapan santai atau laporan tentang orang lain, biasanya melibatkan detail yang kebenarannya belum dipastikan." },
  "dc-m9": { "explanation": "Eager to know or learn something.", "explanationIndo": "Sangat ingin tahu atau mempelajari sesuatu." },
  "dc-m10": { "explanation": "Causing difficulty; hard to do or deal with; causing or feeling embarrassment.", "explanationIndo": "Menyebabkan kesulitan; sulit dilakukan atau dihadapi; menyebabkan atau merasa canggung/malu." },
  "dc-h1": { "explanation": "To secretly listen to a conversation.", "explanationIndo": "Mendengarkan percakapan orang lain secara diam-diam." },
  "dc-h2": { "explanation": "To delay or postpone action; put off doing something.", "explanationIndo": "Menunda-nunda tindakan; mengulur waktu untuk melakukan sesuatu." },
  "dc-h3": { "explanation": "Behaving in a way that suggests one has higher standards or more noble beliefs than is the case.", "explanationIndo": "Berperilaku seolah-olah memiliki standar atau keyakinan yang lebih tinggi daripada yang sebenarnya (munafik)." },
  "dc-h4": { "explanation": "To represent something as being larger, greater, better, or worse than it really is.", "explanationIndo": "Mewakili sesuatu sebagai sesuatu yang lebih besar, lebih hebat, lebih baik, atau lebih buruk dari yang sebenarnya." },
  "dc-h5": { "explanation": "Easily persuaded to believe something; easily tricked.", "explanationIndo": "Mudah dibujuk untuk mempercayai sesuatu; mudah ditipu." },
  "dc-h6": { "explanation": "Performed or occurring as a result of a sudden inner impulse or inclination and without premeditation or external stimulus.", "explanationIndo": "Dilakukan atau terjadi secara tiba-tiba tanpa perencanaan sebelumnya atau rangsangan dari luar." },
  "dc-h7": { "explanation": "Feeling, showing, or expressing sympathy towards others.", "explanationIndo": "Merasakan, menunjukkan, atau mengekspresikan simpati terhadap orang lain." },
  "dc-h8": { "explanation": "Extremely interesting or captivating.", "explanationIndo": "Sangat menarik atau menawan hati." },
  "dc-h9": { "explanation": "Buried or drowning beneath a huge mass of something; feeling unable to handle a situation.", "explanationIndo": "Terkubur atau tenggelam di bawah sesuatu yang sangat banyak; merasa tidak mampu menangani suatu situasi (kewalahan)." },
  "dc-h10": { "explanation": "Unwilling and hesitant; disinclined.", "explanationIndo": "Tidak bersedia dan ragu-ragu; enggan." },
  "dc-x1": { "explanation": "A mode of behavior or way of thought peculiar to an individual.", "explanationIndo": "Suatu mode perilaku atau cara berpikir yang khas/aneh dari seorang individu." },
  "dc-x2": { "explanation": "Present, appearing, or found everywhere.", "explanationIndo": "Hadir, muncul, atau dapat ditemukan di mana-mana." },
  "dc-x3": { "explanation": "Lasting for a very short time; transient.", "explanationIndo": "Berlangsung untuk waktu yang sangat singkat; fana atau sementara." },
  "dc-x4": { "explanation": "The occurrence and development of events by chance in a happy or beneficial way.", "explanationIndo": "Terjadinya peristiwa secara kebetulan dengan cara yang menyenangkan atau menguntungkan." },
  "dc-x5": { "explanation": "(of a voice or words) Sweet or musical; pleasant to hear.", "explanationIndo": "(tentang suara atau kata-kata) Manis atau musikal; sangat merdu dan menyenangkan untuk didengar." },
  "tf-m1": { "explanation": "Existing or available in large quantities; plentiful.", "explanationIndo": "Tersedia dalam jumlah yang besar atau berlimpah." },
  "tf-m2": { "explanation": "To buy or obtain an asset or object for oneself.", "explanationIndo": "Membeli atau mendapatkan sebuah aset atau objek untuk diri sendiri." },
  "tf-m3": { "explanation": "Satisfactory or acceptable in quality or quantity.", "explanationIndo": "Memuaskan atau dapat diterima dalam hal kualitas maupun kuantitas." },
  "tf-m4": { "explanation": "To regard as probable; expect or predict.", "explanationIndo": "Menganggap sesuatu mungkin terjadi; mengharapkan atau memprediksi (mengantisipasi)." },
  "tf-m5": { "explanation": "Clearly visible or understood; obvious.", "explanationIndo": "Sangat terlihat atau mudah dipahami; jelas." },
  "tf-m6": { "explanation": "Prolonged public disagreement or heated discussion.", "explanationIndo": "Ketidaksepakatan publik yang berkepanjangan atau diskusi yang memanas (kontroversi)." },
  "tf-m7": { "explanation": "To transport or carry to a place; to communicate an idea or feeling.", "explanationIndo": "Membawa ke suatu tempat; mengomunikasikan ide atau perasaan (menyampaikan)." },
  "tf-m8": { "explanation": "Of great importance or significance, especially in the success or failure of something.", "explanationIndo": "Sangat penting atau signifikan, terutama dalam menentukan keberhasilan atau kegagalan sesuatu." },
  "tf-m9": { "explanation": "To give special importance or prominence to something in speaking or writing.", "explanationIndo": "Memberikan kepentingan khusus pada sesuatu saat berbicara atau menulis (menekankan)." },
  "tf-m10": { "explanation": "To form an idea of the amount, number, or value of something; to assess.", "explanationIndo": "Membentuk gagasan tentang jumlah, nilai, atau kualitas sesuatu; menilai/mengevaluasi." },
  "tf-h1": { "explanation": "To force or oblige someone to do something.", "explanationIndo": "Memaksa atau mewajibkan seseorang untuk melakukan sesuatu." },
  "tf-h2": { "explanation": "To consist of; to be made up of.", "explanationIndo": "Terdiri dari; dibentuk oleh." },
  "tf-h3": { "explanation": "Existing, happening, or done at the same time.", "explanationIndo": "Ada, terjadi, atau dilakukan pada waktu yang bersamaan." },
  "tf-h4": { "explanation": "To look thoughtfully for a long time at something; to think about deeply.", "explanationIndo": "Melihat atau memikirkan sesuatu dalam waktu yang lama dan mendalam (merenungkan)." },
  "tf-h5": { "explanation": "To become progressively worse.", "explanationIndo": "Menjadi semakin memburuk dari waktu ke waktu." },
  "tf-h6": { "explanation": "To make or become less.", "explanationIndo": "Membuat atau menjadi lebih sedikit/berkurang." },
  "tf-h7": { "explanation": "Involving many carefully arranged parts or details; to explain in detail.", "explanationIndo": "Melibatkan banyak detail yang disusun dengan cermat; menjelaskan secara rinci." },
  "tf-h8": { "explanation": "To try hard to do or achieve something.", "explanationIndo": "Berusaha keras untuk melakukan atau mencapai sesuatu." },
  "tf-h9": { "explanation": "Very great or intense; having or showing great knowledge or insight.", "explanationIndo": "Sangat hebat atau intens; memiliki pengetahuan atau wawasan yang sangat mendalam." },
  "tf-h10": { "explanation": "To rise and fall irregularly in number or amount.", "explanationIndo": "Naik turun secara tidak teratur dalam jumlah atau tingkat (berfluktuasi)." },
  "tf-x1": { "explanation": "Based on, concerned with, or verifiable by observation or experience rather than theory.", "explanationIndo": "Berdasarkan, terkait dengan, atau dapat diverifikasi melalui pengamatan atau pengalaman daripada sekadar teori." },
  "tf-x2": { "explanation": "Never ending or changing; occurring repeatedly.", "explanationIndo": "Tidak pernah berakhir atau berubah; terjadi berulang-ulang (abadi)." },
  "tf-x3": { "explanation": "Having mixed feelings or contradictory ideas about something or someone.", "explanationIndo": "Memiliki perasaan campur aduk atau ide yang bertentangan tentang sesuatu (bimbang)." },
  "tf-x4": { "explanation": "Deviating from what is standard, normal, or expected.", "explanationIndo": "Menyimpang dari apa yang standar, normal, atau yang diharapkan." },
  "tf-x5": { "explanation": "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.", "explanationIndo": "Menangani segala hal secara logis dan realistis berdasarkan pertimbangan praktis daripada teoritis." }
};
